version: '3.7'

services:
  postgresql:
    build: docker/postgresql
    volumes:
      - postgresql_bazafirm:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: bazafirm
      POSTGRES_USER: bazafirm
      POSTGRES_PASSWORD: bazafirm
    ports:
      - "25432:5432"

  minio:
    image: docker.io/bitnami/minio:2021
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '19000:9000'
      - '19001:9001'
    volumes:
      - 'minio_data:/data'


volumes:
  minio_data:
    driver: local
  postgresql_bazafirm:
