server:
  port: 8080

spring:
  application:
    name: firms
    profiles:
      active: ${DEPLOY_ENV}
  datasource:
    url: ${POSTGRESQL_DB_URL}
    username: ${POSTGRESQL_DB_USERNAME}
    password: ${POSTGRESQL_DB_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/baza-firmy-changelog.yaml

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  endpoint: ${AWS_SERVICE_ENDPOINT}
  temp-dir-path: ${TEMP_DIR_PATH}

ceidg:
  ceidg-path: ${CEIDG_PATH}
  token: ${CEIDG_TOKEN}

krs:
  krs-path: ${KRS_PATH}

portal-zewn:
    url: ${PORTAL_ZEW_URL}

smtp:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
